### ISSUE TITLE
using hbbs for 2 servers

### ISSUE THREAD

**Issue by assid2** [rustdesk/rustdesk-server#95] opened 2022-08-11 13:26 UTC
**Describe the bug**
Trying to use 2 rendezvous+relays where server 1 and server 2 speak with each other
ID is not found when connected to the new server 2 

**Describe the environment**
using docker-compose, copy the id_ed25519 files on both
on server 2
hbbs -R <ip of 1> -r host.domain.com:21117 -k _
on server 1
hbbs -R <ip of 2> -r host.domain.com:21117 -k _

**How to Reproduce the bug**
use 2 servers,  in docker compose use the above setting.

**Expected behavior**
hbbs should speak with each other and if the ID of the client to be connected is not found on server 1.. check server 2 and vice versa

**Additional context**
host.domain.com has 2 A records with low TTL
Please feel free to connect with me on discord

**Notes**
 - Please write in english only. If you provide some images in different languages, you're required to write a translation in english.
 - In any case, **NEVER** put here the content if your `id_ed25519` file

**Comment by paspo** [comment] 2022-08-11 13:43
This is not a bug. Simply it's not supposed to work like this.
Multiple hbbs services are not synchronized, there's no shared database (at the moment).

You can have multiple hbbr, with a single hbbs.

**Comment by bigretromike** [comment] 2023-03-18 21:52
@paspo @rustdesk closing ?

**Closed** 2023-03-19 03:08 UTC
Labels: bug
