### ISSUE TITLE
problems with the last update V1.1.10-2 "HBBS Container"

### ISSUE THREAD

**Issue by Joselito1980** [rustdesk/rustdesk-server#358] opened 2024-01-30 15:04 UTC
**Describe the bug**

in the latest update of today, "V.1.1.10-2". "HBBS" container does not start and the following error appears in the log

![image](https://github.com/rustdesk/rustdesk-server/assets/60007170/417bc049-effc-4b38-97c7-04b3a3db4be0)

**Describe the environment**
its installed in docker in a Synology DS 720+ with DSM 7.2.1-69057 Update 4.

i am using this docker compose:

version: '3.9'

services:
  hbbs:
    container_name: Rustdesk_HBBS
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r *******.******:21117
    volumes:
      - /volume1/docker/rustdesk/rustdeskhbbs:/root:rw
    network_mode: "bridge"
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: Rustdesk_HBBR
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - /volume1/docker/rustdesk/rustdeskhbbr:/root:rw
    network_mode: "bridge"
    restart: always

**How to Reproduce the bug**
when i start the proyect appears this error:
![image](https://github.com/rustdesk/rustdesk-server/assets/60007170/55119481-ea26-4d04-ab56-ebd8d307f299)
![image](https://github.com/rustdesk/rustdesk-server/assets/60007170/ddb6f3b8-9c2a-4a3f-9cca-37336ae98be4)
![image](https://github.com/rustdesk/rustdesk-server/assets/60007170/ade43aae-319d-4819-bccd-abdc5d25e1b1)

thanks!!!!!!!

**Comment by GarnetSunset** [comment] 2024-01-30 15:08
Agreed. New update is broken. Same issue on every version.

**Comment by paspo** [comment] 2024-01-30 15:11
Today build added a check for correct size of the secret key, which is causing the error in this case.

The secret key file should NOT have a trailing newline; if there's a newline, with previous release the key is ignored and hbbs is accepting unencrypted connections also.

Now you know that you have to remove such newline at the end of the file. (I think you can use the text editor you have in synology dsm); then restart the container.

**Comment by GarnetSunset** [comment] 2024-01-30 16:30
With love, this should have been in the Changelog, if it's intended behavior!!
Also shouldn't it be possible to snip the possible newline?

**Comment by Joselito1980** [comment] 2024-01-30 17:05
> La compilación de hoy agregó una verificación del tamaño correcto de la clave secreta, lo que está causando el error en este caso.
> 
> El archivo de clave secreta NO debe tener una nueva línea al final; si hay una nueva línea, con la versión anterior la clave se ignora y hbbs también acepta conexiones no cifradas.
> 
> Ahora sabes que debes eliminar esa nueva línea al final del archivo. (Creo que puedes usar el editor de texto que tienes en Synology dsm); luego reinicie el contenedor.

hello!!! in this file? i'm only one line with the token id, or it's other file?
![image](https://github.com/rustdesk/rustdesk-server/assets/60007170/8949c4cc-2eca-4400-a45d-c81282dca9c2)

**Comment by paspo** [comment] 2024-01-30 17:28
you have to look at `id_ed25519` (without `.pub`). 

Please do it using a more advanced editor, capable of distinguish the different kind of newlines (LF or CR+LF). Something like Notepad++ in windows.

**Comment by mariushosting** [comment] 2024-01-30 17:38
> you have to look at `id_ed25519` (without `.pub`).
> 
> Please do it using a more advanced editor, capable of distinguish the different kind of newlines (LF or CR+LF). Something like Notepad++ in windows.

The docker image seems to be bugged since I can replicate the issue on a fresh installation.

**Comment by paspo** [comment] 2024-01-30 17:42
wrong file.

`id_ed25519.pub` contains the PUBLIC KEY.
`id_ed25519` contains the SECRET KEY. You have to look at this file.

(because the public key can be derived from the secret key)

**Comment by Joselito1980** [comment] 2024-01-30 17:48
> wrong file.
> 
> `id_ed25519.pub` contains the PUBLIC KEY. `id_ed25519` contains the SECRET KEY. You have to look at this file.
> 
> (because the public key can be derived from the secret key)
> 
> expected file size should be: 44 bytes for `id_ed25519.pub` 88 bytes for `id_ed25519`

ok thanks.. but in this file its same.. only have a 1 line... 
![image](https://github.com/rustdesk/rustdesk-server/assets/60007170/9398ba88-887d-4ac0-b433-d6351c71062c)

**Comment by mariushosting** [comment] 2024-01-30 17:51
The issue is the latest Rustdesk docker image it's bugged from the beginning. No key file is saved in any folder on a fresh installation because of the malformed key error message. using version :1.1.9 will solve your issue @Joselito1980 

Change:

image: rustdesk/rustdesk-server

with

image: rustdesk/rustdesk-server:1.1.9

in both images then redeploy the stack Until the dev solve the issue

**Comment by Joselito1980** [comment] 2024-01-30 17:54
> The issue is the latest Rustdesk docker image it's bugged from the beginning. No key file is saved in any folder on a fresh installation because of the malformed key error message. using version :1.1.9 will solve your issue @Joselito1980
> 
> Change:
> 
> image: rustdesk/rustdesk-server
> 
> with
> 
> image: rustdesk/rustdesk-server:1.1.9
> 
> in both images then redeploy the stack Until the dev solve the issue

thanks a lot!!! now it's working with the last version, i'm whait to new version! best regards!!!

**Comment by mariushosting** [comment] 2024-01-30 17:55
> > The issue is the latest Rustdesk docker image it's bugged from the beginning. No key file is saved in any folder on a fresh installation because of the malformed key error message. using version :1.1.9 will solve your issue @Joselito1980
> > Change:
> > image: rustdesk/rustdesk-server
> > with
> > image: rustdesk/rustdesk-server:1.1.9
> > in both images then redeploy the stack Until the dev solve the issue
> 
> thanks a lot!!! now it's working with the last version, i'm whait to new version! best regards!!!

with version 1.1.9 is works but not with version 1.1.10 so the latest is the 1.1.10 version but currently bugged.

**Comment by paspo** [comment] 2024-01-30 17:58
> With love, this should have been in the Changelog, if it's intended behavior!! 

This was meant to be a quick and dirty fix for a problem affecting a small number of users.
If the key file is not correct (exactly 88 bytes), hbbs can be used without encryption. 
The only modification is an error indicating the incorrect key with subsequent program stop.

> Also shouldn't it be possible to snip the possible newline?

This can lead to difficult debug: imagine having an extra space at the beginning of the file, the program will have to complain because of a wrong key that looks perfectly normal to anyone looking at the contents.

**Comment by mariushosting** [comment] 2024-01-30 18:00
> > With love, this should have been in the Changelog, if it's intended behavior!!
> 
> This was meant to be a quick and dirty fix for a problem affecting a small number of users. If the key file is not correct (exactly 88 bytes), hbbs can be used without encryption. The only modification is an error indicating the incorrect key with subsequent program stop.
> 
> > Also shouldn't it be possible to snip the possible newline?
> 
> This can lead to difficult debug: imagine having an extra space at the beginning of the file, the program will have to complain because of a wrong key that looks perfectly normal to anyone looking at the contents.

@paspo You can't even write to the folder from the beginning with a fresh RustDesk server installation.

**Comment by GarnetSunset** [comment] 2024-01-30 18:12
Agreed. The key that rustdesk generates on 1.1.10 even after you blow it away, doesnt appear to pass this check. So clearly the key generation code needs to match this check

**Comment by th0mcat** [comment] 2024-01-30 18:26
Can also confirm that rolling back to 1.1.9 fixes the issue.  The `latest` container **will not** generate new Ed25519 keys when the container is restarted or recreated.

**Comment by SirHazza** [comment] 2024-01-30 18:40
Unlucky me, I decided to setup rustdesk **for the first time** this afternoon, and I've been scratching my head as to why I wasn't getting a key generated. Saw this thread and started again with `image: rustdesk/rustdesk-server:1.1.9` and everything is working great now. 

I would highly recommend you remove the latest image ASAP.

**Comment by kiokoman** [comment] 2024-01-30 19:04
same problem here (ubuntu server with precompiled packages .deb), I don't have any space/return on my file but the resulting size is 89B
this was auto-generated by rustdesk in a previous version.
the .pub is 44B

vi id_ed25519 ->

IO+n+dV2L????????????????????????????????????????????????????????????????????????KP46g==
~
~
~
......
"id_ed25519" 1L, 89B              

so i made a new clean installation and there is the same problem, the service hbbs does not start (EXIT / FAILED)  with malformed private key but there is no key generated inside /var/lib/rustdesk-server

**Comment by paspo** [comment] 2024-01-30 19:31
should be fixed by https://github.com/rustdesk/rustdesk-server/pull/361
lets just wait for @rustdesk to test it and merge if ok

**Comment by ECX-mpoellinger** [comment] 2024-01-31 00:46
So even a
`echo -n $(tr -d "\n" < id_ed25519) > id_ed25519`
and afterwards the file size is exact 88 Byte hbbs still fails with "`Malformed private key`"
Seems the check is broken.

**Comment by linuxkidd** [comment] 2024-01-31 03:42
I can confirm that the [1.1.10-3](https://github.com/rustdesk/rustdesk-server/releases/tag/1.1.10-3) release fixed this issue for me.

Thanks to the @rustdesk team for resolving this quickly! :)

**Closed** 2024-01-31 03:52 UTC
Labels: bug

**Comment by Joselito1980** [comment] 2024-01-31 06:05
it's working in the last update! thanks!!!!

**Comment by ECX-mpoellinger** [comment] 2024-01-31 07:53
confirmed. Latest release is working. Thank you @paspo

**Comment by hobhobuk** [comment] 2024-01-31 13:52
Having this issue with a new install of Rust Server, using the windows EXE file to install it..

**Comment by nemiah** [comment] 2024-02-14 15:32
HI, 

the docker images does not seem to have been updated: https://hub.docker.com/r/rustdesk/rustdesk-server/tags

Could you please push the update? @rustdesk
